### ISSUE TITLE
Add 'handlebars' as a peerDependency, so the consuming package can choose it's version and use the same instance

### ISSUE THREAD

**Issue by dietergeerts** [jsreport/jsreport-handlebars#6]
As this package just needs a 'handlebars' engine, it would be better to have it listed as a peer dependency, so the consuming package can choose which version to use, and use the same instance in other parts of the (consuming) application.

**Comment by pofider** [comment]
Sorry for the delay, I didn't notice this issue.

@bjrmatos It makes sense right? I have nothing against doing this.

**Comment by bjrmatos** [comment]
@pofider it sounds good, however this will be the first package in which we require the user to install something extra than just jsreport, if we are ok with this it sounds like a good idea. but if we are going to do this, it makes sense to do it for other extensions too. i'm just afraid that if we go this path we end requiring the user to install too much extra packages in the official jsreport.

**Comment by dietergeerts** [comment]
De decision of which packages to list as peer dependencies should be based on their usage in this package imho. If the use is really internally, and for the user it doesn't matter which version it is etc... then it isn't a peer dependency. In this case, this package is an extension to jsreport, making it possible to use handlebars with it. So these two would be peer dependencies.

**Comment by EvertEt** [comment]
Although I am also a fan of having handlebars as a peerDep, we could also re-export Handlebars which would at least allow the same instance (eg. to use `Handlebars.SafeString`). Would this solution be preferred? It would not solve the version freedom for the consumer.

**Comment by bjrmatos** [comment]
ok, we had some discussion about this and we decided to define it as peer dependency, please follow this [issue](https://github.com/jsreport/jsreport/issues/606) for news, this will be done as part of next release of jsreport
